### ISSUE TITLE
Extended README

### ISSUE THREAD

**Issue by bjmorgan** [arm61/sim_and_scat#11]
It would be nice if the repo README had enough information that people arriving at the Github page knew what they were looking at. Some ideas for things to include:
- What is this repository
- Who is it for
- How is it connected to other resources (e.g. a Zenodo doi? Journal citation?)

**Comment by arm61** [comment]
A bit more information has been added. Cheers for the comment :smile:

**Comment by bjmorgan** [comment]
Also author ORCIDs?

**Comment by arm61** [comment]
changed it now such the links lead to orcid ids rather than personal webpages.

**Comment by bjmorgan** [comment]
Much better idea.
