### ISSUE TITLE
"installation" and requirements

### ISSUE THREAD

**Issue by bjmorgan** [arm61/sim_and_scat#12]
It might be nice to have this entire repo installable as a Python package, i.e. provide a `requirements.txt` and a `setup.py`, to allow `pip install <foo>` (either from GitHub, or from PyPI).

**Comment by arm61** [comment]
Since there are no additional things to install would the `setup.py` not just be linking to the `requirements.txt`?

**Comment by bjmorgan** [comment]
Having `setup.py` would allow you to `pip install` the entire package directly from GitHub or PyPI. Otherwise people need to download, and then run `pip install -r requirements.txt` (two steps).

**Comment by arm61** [comment]
alright, but all that this `setup.py` would need to be is to install the requirements?

**Comment by bjmorgan** [comment]
Yes. And provide metadata / include the README text if you want to host on PyPI.

**Comment by bjmorgan** [comment]
Essentially I think it would be nice to make the install / setup as simple as possible. 

1. (Optional) Set up virtual environment. 
2. `pip install <foo>`

**Comment by arm61** [comment]
I agree. 
And I think if it is a pypi package having them `pip install sim_and_scat` (or whatever the name ends up as) would be nice rather than them having to download the `requirements.txt` and run it. 
I just need to work out how to fold the conda stuff into the `setup.py` as the `nb_conda` package is only in the conda package manager

**Comment by bjmorgan** [comment]
Why is Conda needed? Is this for the notebook extensions?

**Comment by arm61** [comment]
Check out commit https://github.com/arm61/sim_and_scat/commit/f1b4de5f527eb1d44a28a15d7bbcb8b337d777db do see the new installation stuff.

**Comment by bjmorgan** [comment]
Include `Jupyter` in the `requirements.txt`? Or is conda needed elsewhere?

**Comment by arm61** [comment]
like this? https://github.com/arm61/sim_and_scat/commit/918b1b8b88bcd2ad9b44ffb5b5a18c779bd0acae

**Comment by bjmorgan** [comment]
What is the difference between `notebook` and `jupyter`?

**Comment by arm61** [comment]
I think that `notebook` is a subset of `jupyter`. I am not 100 % sure that `notebook` will allow `jupyter notebook` to launch the notebook framework but am fairly sure that `jupyter` will

**Comment by bjmorgan** [comment]
I misread the commit diff. That looks to me like it will work, but haven’t tested using `pip install` in a clean environment.

**Comment by arm61** [comment]
I will test in a clean enviroment just now

**Comment by arm61** [comment]
looks like it works

**Comment by arm61** [comment]
We happy to close this issue now @bjmorgan?
